config/routes.rb
Tickets::Application.routes.draw do

  resources :events
  resources :tickets do 
    post :mark_as_used, on: :member
  end
  devise_for :users

  root 'events#index'

  

end

app/models/event.rb
class Event < ActiveRecord::Base

	validates :title, :description, :place_id, :scheduled_at_time, presence: true
	
  belongs_to :place
	has_many	 :tickets, dependent: :destroy

end

app/models/place.rb
class Place < ActiveRecord::Base
	
	validates :name,:location, :address, :description, presence: true

	has_many 	:events			
	
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	
	require 'digest/md5'

	before_validation :generate_number

	validates :number, presence: true, uniqueness: true
	validates :seat, uniqueness: { scope: :row }
	validates :user_id, :event_id, presence: true

	belongs_to :event
	belongs_to :user

	def self.find_by_number(n)
		return nil if n.to_s.length < 7
		ticket = Ticket.where("number LIKE '#{n}%'")	
	end

	def use_ticket!
		self.update_attribute(:used, true) unless self.used 
	end

	
	private

		def generate_number
			write_attribute(:number, Digest::MD5.hexdigest("#{seat} #{row} #{Time.now}"))
		end

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :recoverable, :rememberable, :registerable, :validatable

  #before_save { self.email = email.downcase }

 	has_many :tickets


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_filter :find_event, only: [:show, :edit, :update, :destroy]
	
	def index #/events/ GET
		@events = Event.all
	end

	def show #/events/1/	GET
		unless @event
			render text: "page not found", status: 404
		end
	end

	def new #/events/new GET
		@event = Event.new
		unless @event.errors.empty?
			@event.save
		end
	end

	def create #/events/ POST	
		@event = Event.create(event_params)
		if @event.errors.empty?
			redirect_to @event
		else
			render 'new'
		end
	end

	def edit #/events/1/edit/ GET
	end

	def update #/events/1/ PATCH
		@event.update_attributes(event_params)
		if @event.errors.empty?
			redirect_to @event
		else
			render 'edit'
		end
	end

	def destroy #/events/1/ DELETE
		@event.destroy
		redirect_to events_path
	end

	private

		def find_event
			@event = Event.where(id: params[:id]).first
		end
	
		def event_params
			params.require(:event).permit(:title, :description, :place_id,
			 															:scheduled_at_time)
		end
	
	end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

	before_filter :authenticate_user!
	before_filter :find_ticket, only: [:show, :mark_as_used, :destroy]
	
	def index
		if current_user.admin?
			@tickets = Ticket.order('created_at DESC')
		else
			@tickets = current_user.tickets
		end
	end

	def show
		unless @ticket
			render text: "page not found", status: 404
		end
	end

	def new
		@ticket = Ticket.new(event_id: params[:event_id]) 
		render(text: "page not found", satus: 404) and return unless @ticket.event
	end

	def mark_as_used
		@ticket.use_ticket!
		respond_to do |format|
			format.html { redirect_to tickets_path }
			format.json { render json: { status: "ok" } }
		end
	end

	def create
		@ticket = Ticket.create(ticket_params.merge({user_id: current_user.id}))
		if @ticket.errors.empty?
			redirect_to @ticket
		else
			p @ticket.errors
			render 'new'	
		end		
	end

	def destroy
		if current_user.admin?
			@ticket.destroy
			redirect_to tickets_path
		end
	end

	private

		def find_ticket
			@ticket = Ticket.where(id: params[:id]).includes(:event).first
		end
	
		def ticket_params
			params.require(:ticket).permit(:event_id, :row, :seat)
		end

end
	

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.haml
%div.container
  %div.row
    - @events.each do |event|
      %div.col-sm-6.col-md-4
        %div.thumbnail
          = image_tag 'http://cdn.pastemagazine.com/www/system/images/photo_albums/charis-tsevis-designs/medium/photo_29872_0.jpg?1295969217'
          %div.caption
            %h3= link_to event.title, event_path(event.id)
            %p= event.description
            %h4 Starting at: #{event.scheduled_at_time.strftime("%d-%B at %R")}
            - if current_user && current_user.admin
              %p
                = link_to 'Edit', edit_event_path(event.id)
                = link_to 'Delete', event_path(event.id), method: :delete, data: { confirm: "Are you shure?" }
            = link_to 'Buy ticket!', new_ticket_path(event_id: event.id), class: "btn btn-success"
  - if current_user && current_user.admin       
    %p= link_to '+ Add event', new_event_path

app/views/events/new.html.haml
%div.container
	%div 
		= simple_form_for (@event) do |e| 
			= e.input :title, label: "title of event, please"
			= e.input :description, label: "description, please"
			= e.date_field :scheduled_at_time, label: "Date:"
			= e.time_field :scheduled_at_time, label: "Time:"
			= e.input :place_id, label: "place_id"
			= e.submit "Create ticket!", class: "btn btn-default"

app/views/events/show.html.haml
%div.container
	%p= @event.title 
	%p= @event.description
	%p starts at #{@event.scheduled_at_time.strftime("%d %b, %Y %I:%M %p")}
	-if current_user && current_user.admin
		%p Tickets bought: #{@event.tickets.count}
	-else
		%p= link_to 'Buy ticket', new_ticket_path(event_id: @event.id)
	%p= link_to 'Back to events', events_path

	%div 
		= simple_form_for @event.tickets.build do |t|
			= t.input :row,  as: :select, collection: (1..17).to_a
			=	t.input :seat, as: :select, collection: (1..30).to_a
			= t.input :event_id, as: :hidden
			= t.submit "Buy it!"

app/views/layouts/_footer.html.haml
%div.footer
  %div.container
    %div.pull-right  
      %p
        %small
          %p Mail to us: #{mail_to 'example@example.com'} 

app/views/layouts/_header.html.haml
%div.navbar.navbar-inverse
  %div.container
    %div.navbar-header
      = link_to "Ticket sochi.com", root_path, class: "navbar-brand"
    %div.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li= link_to "All tickets", tickets_path
          %li.navbar-right= link_to "Log out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign in", user_session_path
          %li= link_to "Sign up", new_user_registration_path
        - if current_user && current_user.admin?
          %li= link_to "Events", events_path
          %p.navbar-text ADMIN
          

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tickets
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "jquery-2.0.3.min", "application"
    = csrf_meta_tags
  %body
    %header= render 'layouts/header'
    = yield
    %footer= render 'layouts/footer'

app/views/tickets/index.html.haml
%div.container
	%div
		- @tickets.each do |ticket|
			%table
				%tr
					%td
						%strong
							= link_to "#{ticket.event.title}", event_path(ticket.event_id) if ticket.event
				%tr
					%td Your row: #{ticket.row}
				%tr
					%td Your seat: #{ticket.seat}
				%tr 	
					%td Your unique number: #{ticket.number}
			 
			= link_to "Show me ticket", ticket_path(ticket)

	%p= link_to '+ buy another ticket', new_ticket_path

app/views/tickets/new.html.haml
%div.container
  %div.well
    %h2
      Ticket to:
      = link_to "#{@ticket.event.title}", event_path(@event)
      %h3 Starts at: #{@ticket.event.scheduled_at_time.strftime("%d of %B at %R")} 
      %h4= @ticket.event.place.name
  %h3 Choose your Row and Seat
  = simple_form_for @ticket do |t|
    = t.input :event_id, as: :hidden
    %p #{t.input :row,  as: :select, collection: (1..17).to_a}  
    %p #{t.input :seat, as: :select, collection: (1..30).to_a}
    = t.submit "Buy it!", class: "btn btn-success"

app/views/tickets/show.html.haml
%div.container
  %div.well 
    %div
      - if @ticket.event
        %h1 Ticket to: #{@ticket.event.title}
        %h3 Starts at: #{@ticket.event.scheduled_at_time.strftime("%d of %B at %R")} 
        %h2
          / %strong  #{@ticket.event.place.name} 
        %h4 row: #{@ticket.row} / seat: #{@ticket.seat}
      
        %h4 number: #{@ticket.number}
    %div
      - if current_user.admin? && !@ticket.used
        .btn.btn-success#use_ticket{ data: { ticket_id: @ticket.id }  } Use Ticket
  %div 
    = link_to "Back to tickets", tickets_path
    - unless current_user.admin
      = link_to "Make refund", tickets_path
      